import { Clause } from '@/types/clause';

// Shared clause data for ClauseManager and contract modal
export const CLAUSES: Clause[] = [
  {
    id: 'noncompete',
    title: 'Non-Compete Clause',
    content: 'The Physician agrees not to engage in any competing practice within 25 miles of {{OrganizationName}} for a period of {{NonCompeteTerm}} years after termination.',
    type: 'standard',
    category: 'restrictive',
    tags: ['non-compete', 'restrictive'],
    applicableProviderTypes: ['physician'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'malpractice',
    title: 'Malpractice Insurance Clause',
    content: 'Employer shall provide malpractice insurance coverage, including tail coverage, for the Physician during the term of employment.',
    type: 'standard',
    category: 'benefits',
    tags: ['insurance', 'malpractice'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'termination',
    title: 'Termination Clause',
    content: 'Either party may terminate this Agreement with {{NoticePeriod}} days written notice.',
    type: 'standard',
    category: 'termination',
    tags: ['termination', 'notice'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'moonlighting',
    title: 'Moonlighting Clause',
    content: 'The Physician may not engage in outside employment (moonlighting) without prior written approval from Employer.',
    type: 'standard',
    category: 'restrictive',
    tags: ['moonlighting', 'restrictive'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'callcoverage',
    title: 'Call Coverage Clause',
    content: 'The Physician shall participate in call coverage as scheduled by Employer and shall receive compensation as outlined in Schedule B.',
    type: 'standard',
    category: 'compensation',
    tags: ['call', 'duties'],
    applicableProviderTypes: ['physician'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'relocation',
    title: 'Relocation Repayment Clause',
    content: 'If the Physician voluntarily terminates employment within 24 months of start date, any relocation bonus paid must be repaid in full.',
    type: 'standard',
    category: 'compensation',
    tags: ['relocation', 'repayment'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'signingbonus',
    title: 'Signing Bonus Repayment Clause',
    content: 'If the Physician voluntarily terminates employment within 12 months of start date, any signing bonus paid must be repaid in full.',
    type: 'standard',
    category: 'compensation',
    tags: ['signing-bonus', 'repayment'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'cme',
    title: 'CME Allowance Clause',
    content: 'The Physician shall be entitled to reimbursement for continuing medical education expenses up to $3,000 per contract year.',
    type: 'standard',
    category: 'benefits',
    tags: ['cme', 'education'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'pto',
    title: 'PTO Policy Clause',
    content: 'The Physician shall be entitled to 20 business days of paid time off per contract year, in addition to 8 paid holidays.',
    type: 'standard',
    category: 'benefits',
    tags: ['pto', 'time-off'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'telemedicine',
    title: 'Telemedicine Clause',
    content: 'The Physician may provide telemedicine services as approved by Employer and in accordance with applicable laws.',
    type: 'standard',
    category: 'other',
    tags: ['telemedicine', 'duties'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'fmv',
    title: 'FMV Exception/Override Clause',
    content: 'All compensation described herein has been determined to be consistent with fair market value for the services provided and is commercially reasonable.',
    type: 'standard',
    category: 'compensation',
    tags: ['fmv', 'compensation'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'retention',
    title: 'Retention Bonus Clause',
    content: 'The Physician shall be eligible for a retention bonus as outlined in Schedule B, subject to continued employment.',
    type: 'standard',
    category: 'compensation',
    tags: ['retention', 'bonus'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'productivity',
    title: 'Productivity Incentive Clause',
    content: 'The Physician shall be eligible for productivity-based compensation as described in Schedule B.',
    type: 'standard',
    category: 'compensation',
    tags: ['productivity', 'incentive'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['productivity', 'hybrid'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'restrictive',
    title: 'Restrictive Covenant Clause',
    content: 'The Physician agrees to abide by all confidentiality, non-solicitation, and non-disparagement provisions as set forth in this Agreement.',
    type: 'standard',
    category: 'restrictive',
    tags: ['restrictive', 'covenant'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  // New Provider Compensation Clauses
  {
    id: 'base-compensation',
    title: 'Base Compensation Clause',
    content: 'Provider shall receive an annual base salary of {{BaseSalary}} payable in accordance with Employer\'s standard payroll schedule.',
    type: 'standard',
    category: 'compensation',
    tags: ['base-salary', 'compensation'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'productivity-bonus',
    title: 'Productivity Bonus Clause',
    content: 'For wRVUs exceeding {{wRVUTarget}}, Provider shall receive {{ConversionFactor}} per additional wRVU, calculated and paid quarterly.',
    type: 'standard',
    category: 'compensation',
    tags: ['productivity', 'wrvu', 'bonus'],
    applicableProviderTypes: ['physician'],
    applicableCompensationModels: ['productivity', 'hybrid'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'fte-assignment',
    title: 'FTE Assignment Clause',
    content: 'Provider shall be assigned {{ClinicalFTE}} clinical FTE and {{AdministrativeFTE}} administrative FTE, with total FTE not exceeding {{TotalFTE}}.',
    type: 'standard',
    category: 'compensation',
    tags: ['fte', 'assignment', 'clinical', 'administrative'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'signing-bonus-dynamic',
    title: 'Signing Bonus Clause',
    content: 'Provider shall receive a signing bonus of {{SigningBonus}} payable within 30 days of start date, subject to repayment terms outlined in Section 8.2.',
    type: 'standard',
    category: 'compensation',
    tags: ['signing-bonus', 'bonus'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'retention-bonus-dynamic',
    title: 'Retention Bonus Clause',
    content: 'Provider shall be eligible for retention bonus of {{RetentionBonus}} upon completion of {{RetentionPeriod}} of continuous employment.',
    type: 'standard',
    category: 'compensation',
    tags: ['retention-bonus', 'bonus'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'confidentiality-static',
    title: 'Confidentiality Agreement',
    content: 'Provider acknowledges and agrees to maintain strict confidentiality of all patient information, business records, and proprietary information of Employer in accordance with HIPAA and other applicable laws.',
    type: 'standard',
    category: 'restrictive',
    tags: ['confidentiality', 'hipaa'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'termination-notice',
    title: 'Termination Notice Requirements',
    content: 'Either party may terminate this Agreement with 90 days written notice. Provider shall continue to perform all duties during the notice period unless otherwise directed by Employer.',
    type: 'standard',
    category: 'termination',
    tags: ['termination', 'notice'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'professional-liability',
    title: 'Professional Liability Insurance',
    content: 'Employer shall provide professional liability insurance coverage of $1,000,000 per occurrence and $3,000,000 aggregate, including tail coverage upon termination.',
    type: 'standard',
    category: 'benefits',
    tags: ['malpractice', 'insurance', 'liability'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'cme-requirements',
    title: 'CME Requirements and Allowance',
    content: 'Provider shall complete {{CMEDays}} days of continuing medical education annually and shall be entitled to reimbursement of up to {{CMEAmount}} for approved CME expenses.',
    type: 'standard',
    category: 'benefits',
    tags: ['cme', 'education', 'requirements'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  },
  {
    id: 'quality-bonus',
    title: 'Quality Performance Bonus',
    content: 'Provider shall be eligible for quality performance bonus of up to {{QualityBonus}} based on achievement of quality metrics as outlined in Schedule C.',
    type: 'standard',
    category: 'compensation',
    tags: ['quality', 'bonus', 'performance'],
    applicableProviderTypes: ['physician', 'advanced-practitioner'],
    applicableCompensationModels: ['base', 'productivity', 'hybrid', 'hospitalist', 'leadership'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    version: '1.0.0'
  }
]; 